version: '3.8'

services:
  php:
    container_name: laravel-demo-php
    build: 
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: local
    volumes:
    - ./src:/var/www

  nginx:
    image: nginx
    container_name: laravel-demo-nginx
    ports:
    - 8000:80
    volumes:
    - ./src:/var/www
    - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: laravel-demo-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: develop
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
